{{- if and .Values.frontend.enabled .Values.frontend.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cifo.fullname" . }}-frontend
  labels:
    {{- include "cifo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "cifo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
