{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cifo.fullname" . }}-frontend
  labels:
    {{- include "cifo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "cifo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
