{{- if and .Values.backend.enabled .Values.backend.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cifo.fullname" . }}-backend
  labels:
    {{- include "cifo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "cifo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
