{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cifo.fullname" . }}-backend
  labels:
    {{- include "cifo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "cifo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
