apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cifo-production

namePrefix: prod-

resources:
  - ../../base

commonLabels:
  environment: production

images:
  - name: cifo-backend
    newName: ghcr.io/cifo/backend
    newTag: v1.0.0
  - name: cifo-frontend
    newName: ghcr.io/cifo/frontend
    newTag: v1.0.0
  - name: cifo-ai-service
    newName: ghcr.io/cifo/ai-service
    newTag: v1.0.0
