{{- if and .Values.aiService.enabled .Values.aiService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aiService.serviceAccount.name }}
  labels:
    {{- include "cifo.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-service
{{- end }}
